name: Deploy Qualisoft to Production

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Connexion SSH et Mise à jour
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            cd /app/qualisoft/qualisoft-rd-2030
            git pull origin main
            
            # 1. On force la reconstruction du bon service (qualisoft-ui)
            # On utilise --force-recreate pour être sûr que la 404 disparaisse
            docker compose up -d --build --force-recreate qualisoft-ui
            
            # 2. Nettoyage des images inutiles pour ne pas saturer le serveur OVH
            docker image prune -f